services:
  - type: web
    name: ekondo-expense-mgt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:5000 app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: "mysql+pymysql://Super_Admin:Emmanate1$$@localhost/ekondo_db"
      - key: REDIS_URL
        value: "rediss://red-cte9cp5umphs73bb5us0:ALDTjn1BkqqHvAJ2AufpB5JBoldkuAc7@oregon-redis.render.com:6379"
      - key: SECRET_KEY
        value: "eKM_5eCur3t-K3y#2024!"
